micronaut:
  application:
    name: lojaService
  server:
    port: 8081
netty:
  default:
    allocator:
      max-order: 3

redis:
  uri: redis://localhost:6379
  caches:
    veiculos:

#kafka:
#  bootstrap:
#    servers: localhost:9092